//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webEntityOkul
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        public Ogretmenler()
        {
            this.Siniflar = new HashSet<Siniflar>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public int KursID { get; set; }
    
        public virtual Kurslar Kurslar { get; set; }
        public virtual ICollection<Siniflar> Siniflar { get; set; }
    }
}
